language: python
python:
#  - "2.5"
#  - "2.6"
  - "2.7"
#  - "3.2"
install:
 - sudo apt-get install -qq python-psycopg2 python-sendfile
 - pip install cython greenlet -q --use-mirrors
 - cython --version
 - python setup.py install
script: cd greentest && python testrunner.py
notifications:
  email:
    recipients:
      - denis.bilenko@gmail.com
    on_success: change
    on_failure: change
